apiVersion: v1
kind: Service
metadata:
  name: db
  labels:
    name: service-postgres
    app: votingdemo
spec:
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    name: pod-postgres
    app: votingdemo