apiVersion: v1
kind: Service
metadata:
  name: votingresultapp
  labels:
    name: service-votingresultapp
    app: demovoting
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30005
  selector:
    name: pod-votingresultapp
    app: votingdemo