apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    name: service-redis
    app: votindemo
spec:
  ports:
    - port: 6379
      targetPort: 6379
  selector:
    name: pod-redis
    app: votingdemo
