apiVersion: v1
kind: Service
metadata:
  name: votingapp
  labels:
    name: service-votingapp
    app: demovoting
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30004
  selector:
    name: pod-votingapp
    app: votingdemo