apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-votingresultapp
  labels:
    name: deployment-votingresultapp
    app: votingdemo
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      name: pod-votingresultapp
      app: votingdemo
  template:
    metadata:
      name: pod-votingresultapp
      labels:
        name: pod-votingresultapp
        app: votingdemo
    spec:
      containers:
        - name: votingresultapp
          image: registry.cn-hangzhou.aliyuncs.com/wangbs/examplevotingapp_result-app
          ports:
            - containerPort: 80