apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
  labels:
    tier: db-tier
spec:
  replicas: 33
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      tier: db-tier
  template:
    metadata:
      name: postgres
      labels:
        tier: db-tier
    spec:
      containers:
        - name: postgres
          image: postgres:9.6.18
          env:
            - name: POSTGRES_PASSWORD
              value: mysecretpassword
