apiVersion: v1
kind: Pod
metadata:
  name: pod-votingapp
  labels:
    name: pod-votingapp
    app: votingdemo
spec:
  containers:
    - name: votingapp
      image: dockersamples/examplevotingapp_vote
      ports:
        - containerPort: 80