apiVersion: v1
kind: Pod
metadata:
  name: pod-redis
  labels:
    name: pod-redis
    app: votingdemo
spec:
  containers:
    - name: redis
      image: redis:6.0.6
      ports:
        - containerPort: 6379