apiVersion: v1
kind: Pod
metadata:
  name: pod-votingresultapp
  labels:
    name: pod-votingresultapp
    app: votingdemo
spec:
  containers:
    - name: votingresultapp
      image: registry.cn-hangzhou.aliyuncs.com/wangbs/examplevotingapp_result-app
      ports:
        - containerPort: 80