apiVersion: v1
kind: Pod
metadata:
  name: pod-votingresultapp
  labels:
    name: pod-votingresultapp
    app: votingdemo
spec:
  containers:
    - name: votingresultapp
      image: dockersamples/examplevotingapp_result
      ports:
        - containerPort: 80