apiVersion: v1
kind: Pod
metadata:
  name: pod-votingworker
  labels:
    name: pod-votingworker
    app: votingdemo
spec:
  containers:
    - name: votingworker
      image: registry.cn-hangzhou.aliyuncs.com/wangbs/examplevotingapp_worker