apiVersion: v1
kind: Pod
metadata:
  name: pod-postgres
  labels:
    name: pod-postgres
    app: votingdemo
spec:
  containers:
    - name: postgres
      image: postgres:9.6.18
      ports:
        - containerPort: 5432
      env:
        - name: POSTGRES_USER
          value: "postgres"
        - name: POSTGRES_PASSWORD
          value: "postgres"