apiVersion: v1
kind: Pod
metadata:
  name: pod-votingapp
  labels:
    name: pod-votingapp
    app: votingdemo
spec:
  containers:
    - name: votingapp
      image: registry.cn-hangzhou.aliyuncs.com/wangbs/examplevotingapp_voting-app
      ports:
        - containerPort: 80