apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: postgres-replicaset
  labels:
    tier: db-tier
spec:
  selector:
    matchLabels:
      tier: db-tier
  replicas: 12
  template:
    metadata:
      name: postgres
      labels:
        tier: db-tier
    spec:
      containers:
        - name: postgres
          image: postgres
          env:
            - name: POSTGRES_PASSWORD
              value: mysecretpassword